name: "Build and Deploy to Azure Container Instances"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Required repo secrets:
# - AZURE_CREDENTIALS
# - ACR_NAME
# - ACR_USERNAME
# - ACR_PASSWORD
# - AZURE_RESOURCE_GROUP

env:
  IMAGE_NAME: my-webapp
  AZURE_REGION: eastus
  CONTAINER_PORT: "3001"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login "${{ secrets.ACR_NAME }}.azurecr.io" \
            --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build and push image to ACR
        shell: bash
        run: |
          IMAGE_TAG="${GITHUB_SHA}"
          FULL_IMAGE="${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
          docker build -t "${FULL_IMAGE}" .
          docker push "${FULL_IMAGE}"
          echo "FULL_IMAGE=${FULL_IMAGE}" >> "$GITHUB_ENV"

      - name: Create DNS-safe ACI name (lowercase, hyphenated)
        shell: bash
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          REPO_LC="${GITHUB_REPOSITORY,,}"
          REPO_BASENAME="${REPO_LC##*/}"
          [ -z "$OWNER_LC" ] && OWNER_LC="ghuser"
          [ -z "$REPO_BASENAME" ] && REPO_BASENAME="app"
          NAME_RAW="${OWNER_LC}-${REPO_BASENAME}-web-${GITHUB_RUN_NUMBER}"
          NAME_SAN="${NAME_RAW//[^a-z0-9-]/-}"
          NAME_SAN="${NAME_SAN,,}"
          NAME_SAN="${NAME_SAN%-}"
          NAME_SAN="${NAME_SAN#-}"
          ACI_NAME="${NAME_SAN:0:60}"
          echo "ACI_NAME=${ACI_NAME}" >> "$GITHUB_ENV"
          echo "DNS_LABEL=${ACI_NAME}" >> "$GITHUB_ENV"
          echo "Using ACI_NAME=${ACI_NAME}"

      - name: Deploy to Azure Container Instances
        uses: azure/cli@v2
        with:
          inlineScript: |
            az container create \
              --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
              --name "${{ env.ACI_NAME }}" \
              --image "${{ env.FULL_IMAGE }}" \
              --registry-login-server "${{ secrets.ACR_NAME }}.azurecr.io" \
              --registry-username "${{ secrets.ACR_USERNAME }}" \
              --registry-password "${{ secrets.ACR_PASSWORD }}" \
              --dns-name-label "${{ env.DNS_LABEL }}" \
              --ports ${{ env.CONTAINER_PORT }} \
              --os-type Linux \
              --cpu 1 \
              --memory 1.5 \
              --location "${{ env.AZURE_REGION }}" \
              --restart-policy Always

      - name: Show App URL
        run: |
          echo "Your app (once ACI is Running) ->"
          echo "  http://${{ env.DNS_LABEL }}.${{ env.AZURE_REGION }}.azurecontainer.io:${{ env.CONTAINER_PORT }}"

